# train_blockage_gru.py
#
# One-shot offline training script. Run this ONCE to produce
# blockage_gru.onnx in the same directory. After it runs, you can
# uninstall torch if you want — the live Flask app only needs
# onnxruntime.
#
# Training data source: a physically-motivated statistical THz
# channel model with Rician fading, bursty blockage events, and
# slow distance-driven SNR drift. Deliberately NOT generated by
# the same simulator the dashboard uses, so the GRU does not just
# memorize the dashboard's own math.
#
# Usage:
#     python train_blockage_gru.py
#
# Outputs:
#     blockage_gru.onnx      (the inference artifact)
#     blockage_gru_meta.json (training metadata, sanity check)

import json
import math
import os
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

# ------------------------------------------------------------------
# Config
# ------------------------------------------------------------------
SEQ_LEN        = 16        # fixed training window
N_SEQUENCES    = 20000     # training set size
N_VAL          = 2000      # validation set size
HIDDEN_UNITS   = 16
BATCH_SIZE     = 128
EPOCHS         = 30
LR             = 2e-3
SEED           = 42
OUT_ONNX       = "blockage_gru.onnx"
OUT_META       = "blockage_gru_meta.json"

torch.manual_seed(SEED)
np.random.seed(SEED)


# ------------------------------------------------------------------
# Synthetic THz channel model
#
# SNR at any instant is modeled as:
#     SNR(t) = SNR_ref - FSPL(d(t)) + fading(t) - blockage_attenuation(t)
#
# - SNR_ref         : constant offset (TX EIRP + RX gain - noise floor)
# - FSPL(d)         : log10 of distance, slowly varying
# - fading          : Rician process (dominant LOS + multipath)
# - blockage        : bursty, on/off, with a soft rise/fall envelope
# ------------------------------------------------------------------
SNR_REF_DB = 145.0

def _fspl_db(distance_m):
    d = np.maximum(distance_m, 0.1)
    return 20.0 * np.log10(d) + 81.99

def _rician_sequence(n, K_db=6.0, sigma_db=1.5):
    """
    Rician fading simplified to a scalar SNR perturbation in dB.
    K_db is the ratio of LOS to scattered power.
    """
    K = 10 ** (K_db / 10.0)
    los_amp = math.sqrt(K / (K + 1))
    scat_amp = math.sqrt(1.0 / (K + 1))
    # Scattered component: complex Gaussian
    i = np.random.randn(n) * scat_amp * sigma_db
    q = np.random.randn(n) * scat_amp * sigma_db
    # Envelope in dB relative to LOS
    env = np.sqrt((los_amp + i) ** 2 + q ** 2)
    return 20.0 * np.log10(np.maximum(env, 1e-6))

def _blockage_sequence(n, p_start=0.15, duration_range=(4, 10)):
    """
    Bursty blockage. Returns (mask, attenuation_db).
    mask[i] is 1 while a blockage is active, 0 otherwise.
    attenuation_db[i] is the extra path loss from the blockage.
    """
    mask = np.zeros(n, dtype=np.float32)
    atten = np.zeros(n, dtype=np.float32)
    i = 0
    while i < n:
        if np.random.rand() < p_start:
            dur = np.random.randint(duration_range[0], duration_range[1] + 1)
            depth = 20.0 + np.random.rand() * 30.0   # 20-50 dB excess loss
            # Soft rise/fall over 1-2 samples
            rise = min(2, dur // 2)
            fall = min(2, dur // 2)
            for k in range(dur):
                idx = i + k
                if idx >= n:
                    break
                if k < rise:
                    atten[idx] = depth * (k + 1) / rise
                elif k >= dur - fall:
                    atten[idx] = depth * (dur - k) / fall
                else:
                    atten[idx] = depth
                mask[idx] = 1.0
            i += dur
        else:
            i += 1
    return mask, atten

def _distance_drift(n, start_m, end_m=None, rate_m_per_sample=0.05):
    """Slowly varying distance; simulates the drone drifting."""
    if end_m is None:
        end_m = start_m + rate_m_per_sample * n * (1.0 if np.random.rand() < 0.5 else -1.0)
    dist = np.linspace(start_m, max(end_m, 2.0), n)
    # Add small random walk on top
    dist += np.cumsum(np.random.randn(n) * 0.02)
    return np.maximum(dist, 2.0)

def generate_sequence():
    """Returns (snr_seq[SEQ_LEN], label 0/1)."""
    # Pick a starting distance: near (10 m) to far (60 m)
    d_start = np.random.uniform(5.0, 55.0)
    d_end = d_start + np.random.randn() * 15.0
    d_end = max(min(d_end, 80.0), 3.0)
    dist = _distance_drift(SEQ_LEN, d_start, d_end)

    fading = _rician_sequence(SEQ_LEN,
                              K_db=np.random.uniform(3.0, 12.0),
                              sigma_db=np.random.uniform(0.5, 3.0))
    mask, atten = _blockage_sequence(SEQ_LEN)

    snr = SNR_REF_DB - _fspl_db(dist) + fading - atten
    snr += np.random.randn(SEQ_LEN) * 0.5   # small AWGN on the SNR estimate

    # Label: 1 if a blockage is active at the END of the window
    # (this is what we want the GRU to predict). We also widen the
    # positive class to include windows where a blockage is about
    # to start within the next 2 samples — this teaches the GRU to
    # fire slightly early, which is the whole point of prediction.
    label = 0.0
    if mask[-1] > 0.5 or mask[-2] > 0.5:
        label = 1.0

    return snr.astype(np.float32), label


def build_dataset(n):
    X = np.zeros((n, SEQ_LEN, 1), dtype=np.float32)
    Y = np.zeros((n, 1), dtype=np.float32)
    for i in range(n):
        s, l = generate_sequence()
        X[i, :, 0] = s
        Y[i, 0] = l
    return X, Y


# ------------------------------------------------------------------
# Model
# ------------------------------------------------------------------
class BlockageGRU(nn.Module):
    def __init__(self, hidden=16):
        super().__init__()
        self.gru = nn.GRU(input_size=1, hidden_size=hidden,
                          num_layers=1, batch_first=True)
        self.head = nn.Linear(hidden, 1)

    def forward(self, x):
        # x: (B, SEQ_LEN, 1)
        out, _ = self.gru(x)
        last = out[:, -1, :]
        return torch.sigmoid(self.head(last))


# ------------------------------------------------------------------
# Training
# ------------------------------------------------------------------
def main():
    print("[train] generating training data ...")
    Xtr, Ytr = build_dataset(N_SEQUENCES)
    Xva, Yva = build_dataset(N_VAL)

    # Normalize inputs: shift and scale so the GRU sees stable values
    mu  = float(Xtr.mean())
    sig = float(Xtr.std() + 1e-6)
    Xtr = (Xtr - mu) / sig
    Xva = (Xva - mu) / sig

    print(f"[train] dataset: tr={Xtr.shape} va={Xva.shape} mean={mu:.2f} std={sig:.2f}")
    print(f"[train] positive rate: tr={Ytr.mean():.3f} va={Yva.mean():.3f}")

    #device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    # This model is tiny (~2k parameters). CPU training is faster
    # than GPU for a network this size, and it sidesteps CUDA
    # compute-capability mismatches on older GPUs.
    device = torch.device("cpu")
    model = BlockageGRU(HIDDEN_UNITS).to(device)
    opt = optim.Adam(model.parameters(), lr=LR)
    lossf = nn.BCELoss()

    Xtr_t = torch.from_numpy(Xtr).to(device)
    Ytr_t = torch.from_numpy(Ytr).to(device)
    Xva_t = torch.from_numpy(Xva).to(device)
    Yva_t = torch.from_numpy(Yva).to(device)

    n_batches = max(1, Xtr_t.size(0) // BATCH_SIZE)
    best_val = float("inf")

    for ep in range(EPOCHS):
        model.train()
        perm = torch.randperm(Xtr_t.size(0), device=device)
        total = 0.0
        for b in range(n_batches):
            idx = perm[b * BATCH_SIZE:(b + 1) * BATCH_SIZE]
            if idx.numel() == 0:
                continue
            opt.zero_grad()
            pred = model(Xtr_t[idx])
            loss = lossf(pred, Ytr_t[idx])
            loss.backward()
            opt.step()
            total += float(loss.item())

        model.eval()
        with torch.no_grad():
            val_pred = model(Xva_t)
            val_loss = float(lossf(val_pred, Yva_t).item())
            # Confusion matrix at threshold 0.5
            pred_bin = (val_pred > 0.5).float()
            tp = float(((pred_bin == 1) & (Yva_t == 1)).sum().item())
            fp = float(((pred_bin == 1) & (Yva_t == 0)).sum().item())
            fn = float(((pred_bin == 0) & (Yva_t == 1)).sum().item())
            tn = float(((pred_bin == 0) & (Yva_t == 0)).sum().item())
            prec = tp / max(tp + fp, 1e-6)
            rec  = tp / max(tp + fn, 1e-6)
            acc  = (tp + tn) / max(tp + tn + fp + fn, 1e-6)

        marker = ""
        if val_loss < best_val:
            best_val = val_loss
            torch.save(model.state_dict(), "_best.pt")
            marker = "  *saved*"

        print(f"[train] ep {ep+1:02d}  tr_loss={total/n_batches:.4f}  "
              f"va_loss={val_loss:.4f}  acc={acc:.3f}  prec={prec:.3f}  rec={rec:.3f}{marker}")

    # Reload best and export
    model.load_state_dict(torch.load("_best.pt", map_location=device))
    model.eval()

    # Sanity predictions on a few example sequences
    print("\n[train] example predictions:")
    with torch.no_grad():
        for k in range(3):
            s, l = generate_sequence()
            s_norm = (s - mu) / sig
            inp = torch.from_numpy(s_norm.reshape(1, SEQ_LEN, 1)).to(device)
            p = float(model(inp).item())
            print(f"  true_label={int(l)}  pred={p:.3f}  snr_window=[{s[0]:.1f} ... {s[-1]:.1f}]")

    # Export to ONNX
    dummy = torch.zeros(1, SEQ_LEN, 1, device=device)
    torch.onnx.export(
        model, dummy, OUT_ONNX,
        input_names=["snr_window"],
        output_names=["blockage_prob"],
        dynamic_axes={"snr_window": {0: "batch"}, "blockage_prob": {0: "batch"}},
        opset_version=13,
    )

    meta = {
        "seq_len": SEQ_LEN,
        "hidden_units": HIDDEN_UNITS,
        "input_mean": mu,
        "input_std": sig,
        "best_val_loss": best_val,
        "n_train": N_SEQUENCES,
        "n_val": N_VAL,
    }
    with open(OUT_META, "w") as f:
        json.dump(meta, f, indent=2)

    try:
        os.remove("_best.pt")
    except OSError:
        pass

    print(f"\n[train] exported {OUT_ONNX}")
    print(f"[train] exported {OUT_META}")
    print("[train] done. You can now restart the Flask service.")


if __name__ == "__main__":
    main()
